export const USER_CONSTANTS = {
  AUTH_LOGIN : "AUTH_LOGIN",
  AUTH_REGISTER : "AUTH_REGISTER",
  SET_USER_DETAILS : "SET_USER_DETAILS",
  COMMIT_USER_LOCAL : "COMMIT_USER_LOCAL",
  USER_LOGOUT : "USER_LOGOUT",
  INITIALIZE_USER: "INITIALIZE_USER"
}

export const CLASS_CONSTANTS = {
  QUIZ_QUESTIONS: "QUIZ_QUESTIONS"
}

export const ADMIN_CONSTANTS = {
  SET_CLASSES: "SET_CLASSES",
  SET_DETAILED_CLASSES: "SET_DETAILED_CLASSES"
}